AizantIT_PharmaApp/Areas/Regulatory/Controllers/RegulatoryMainController.cs
using Aizant_API_Entities;
using AizantIT_PharmaApp.Areas.Regulatory.Controllers.RegulatoryLinq;
using AizantIT_PharmaApp.Areas.Regulatory.Models;
using AizantIT_PharmaApp.Areas.Regulatory.Models.RegulatoryViewModel;
using AizantIT_PharmaApp.Areas.Regulatory.Models.Reports;
using AizantIT_PharmaApp.Areas.Regulatory.Models.Reports.DataSource;
using AizantIT_PharmaApp.Common;
using AizantIT_PharmaApp.Common.CustomFilters;
using AizantIT_PharmaApp.Controllers.Aizant_BL;
using AizantIT_PharmaApp.Models.Common;
using CrystalDecisions.CrystalReports.Engine;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Core.Objects;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using static Aizant_Enums.AizantEnums;

namespace AizantIT_PharmaApp.Areas.Regulatory.Controllers
{
    [Route("Regulatory/RegulatoryMainController/{action}")]
    [RouteArea]
    [CustAuthentication]
    public class RegulatoryMainController : Controller
    {
        // GET: Regulatory/RegulatoryDashBoard
        [CustAuthorization((int)Modules.RA,
            (int)RA_UserRole.RA_Admin,
            (int)RA_UserRole.RA_Lead,
            (int)RA_UserRole.RA_Approver,
            (int)RA_UserRole.RA_HOD)]
        public ActionResult RegulatoryDashBoard()
        {
            bool PendingCard = false;
            bool RevertedCard = false;
            RegulatoryDashBoard objregulatoryDashBoard = new RegulatoryDashBoard();
            var EmpID = Convert.ToInt32((Session["UserDetails"] as DataSet).Tables[0].Rows[0]["EmpID"]);
            string[] ModuleRoles = (string[])Session["EmpModuleRoles"];
            var dbContext = new AizantIT_DevEntities();
            List<PendingListItems> Pendinglist = new List<PendingListItems>();
            List<RevertListItems> Revertlist = new List<RevertListItems>();

            if (ModuleRoles.Contains(((int)Aizant_Enums.AizantEnums.RA_UserRole.RA_Approver).ToString()))
            {
                PendingCard = true;
                int DossierPendingCount = dbContext.AizantIT_ProductDossier.Where(a => a.CurrentStatus == 2 && a.ApproverEmpID == EmpID).Count();
                int DeficiencyPendingCount = dbContext.AizantIT_DeficiencyMaster.Where(a => a.CurrentStatus == 2 && a.ApproverID == EmpID).Count();

                if (DossierPendingCount > 0)//Dossier Pending
                {
                    Pendinglist.Add(new PendingListItems(DossierPendingCount, "/Regulatory/RegulatoryMain/DossierMainList?ShowType=4", "Product Details for Approval"));
                    objregulatoryDashBoard.PendingTotalCount += DossierPendingCount;
                }
                if (DeficiencyPendingCount > 0)//Deficiency Pending
                {

                    Pendinglist.Add(new PendingListItems(DeficiencyPendingCount, "/Regulatory/RegulatoryMain/DeficiencyMainList?ShowType=14", "Deficiency"));
                    objregulatoryDashBoard.PendingTotalCount += DeficiencyPendingCount;
                }
            }
            if (ModuleRoles.Contains(((int)Aizant_Enums.AizantEnums.RA_UserRole.RA_Lead).ToString()))
            {
                RevertedCard = true;
                PendingCard = true;
                int DossierRevertCount = dbContext.AizantIT_ProductDossier.Where(a => a.CurrentStatus == 4 && a.AuthorEmpID == EmpID).Count();//Current Status==4(Revert)
                int DossierPendingCount = dbContext.AizantIT_ProductDossier.Where(a => new int[] { 5, 6, 7 }.Contains(a.CurrentStatus) && a.AuthorEmpID == EmpID).Count();
                int DeficiencyRevertCount = dbContext.AizantIT_DeficiencyMaster.Where(a => a.CurrentStatus == 4 && a.AuthorID == EmpID).Count();//Current Status ==4(Revert)

                if (DossierRevertCount > 0)//Product Revert
                {
                    Revertlist.Add(new RevertListItems(DossierRevertCount, "/Regulatory/RegulatoryMain/DossierMainList?ShowType=2", "Product Details"));
                    objregulatoryDashBoard.RevertTotalCount += DossierRevertCount;
                }
                if (DossierPendingCount > 0)//Product Pending
                {
                    Pendinglist.Add(new PendingListItems(DossierPendingCount, "/Regulatory/RegulatoryMain/DossierMainList?ShowType=9", "Product Completion Pending"));
                    objregulatoryDashBoard.PendingTotalCount += DossierPendingCount;
                }
                if (DeficiencyRevertCount > 0)//Deficiency Revert
                {
                    Revertlist.Add(new RevertListItems(DeficiencyRevertCount, "/Regulatory/RegulatoryMain/DeficiencyMainList?ShowType=13", "Deficiency"));
                    objregulatoryDashBoard.RevertTotalCount += DeficiencyRevertCount;
                }
                objregulatoryDashBoard.RaLead = Convert.ToInt32(RA_UserRole.RA_Lead);
            }
            if (ModuleRoles.Contains(((int)Aizant_Enums.AizantEnums.RA_UserRole.RA_HOD).ToString()))
            {
                PendingCard = true;
                int IsObservationPendingCount = (from DF in dbContext.AizantIT_DF_Observation
                                                 join DEF in dbContext.AizantIT_DeficiencyMaster on DF.DeficiencyID equals DEF.DeficiencyID
                                                 where DF.CurrentStatus == 1 && DF.ResponsiblePersonEmpID == EmpID && DF.Status == 1 && DEF.CurrentStatus == 5
                                                 select DF).Count();

                int IsObservationCompleteCount = (from DF in dbContext.AizantIT_DF_Observation
                                                  join DEF in dbContext.AizantIT_DeficiencyMaster on DF.DeficiencyID equals DEF.DeficiencyID
                                                  where DF.CurrentStatus == 2 && DF.ResponsiblePersonEmpID == EmpID && DF.Status == 1 && DEF.CurrentStatus == 5
                                                  select DF).Count();

                if (IsObservationPendingCount > 0)//Observations to Accept
                {
                    Pendinglist.Add(new PendingListItems(IsObservationPendingCount, "/Regulatory/RegulatoryMain/ObservationMainList?ShowType=18", "Observation to Accept"));
                    objregulatoryDashBoard.PendingTotalCount += IsObservationPendingCount;
                }
                if (IsObservationCompleteCount > 0)//Observations to Complete
                {
                    Pendinglist.Add(new PendingListItems(IsObservationCompleteCount, "/Regulatory/RegulatoryMain/ObservationMainList?ShowType=19", "Observation to Close"));
                    objregulatoryDashBoard.PendingTotalCount += IsObservationCompleteCount;
                }
                objregulatoryDashBoard.RaHod = Convert.ToInt32(RA_UserRole.RA_HOD);
            }
            objregulatoryDashBoard.pendingListItems = Pendinglist;
            objregulatoryDashBoard.revertListItems = Revertlist;

            objregulatoryDashBoard.PendingCard = PendingCard;
            objregulatoryDashBoard.RevertedCard = RevertedCard;
            return View(objregulatoryDashBoard);
        }

        #region Dossier
        private DateTime? getDateValue(string strDate)
        {
            if (strDate == "" || strDate == null)
            {
                return null;
            }
            else
            {
                return Convert.ToDateTime(strDate);
            }
        }
        public PartialViewResult _ViewDossierDetails(int DossierID)
        {
            var EmpID = Convert.ToInt32((Session["UserDetails"] as DataSet).Tables[0].Rows[0]["EmpID"]);
            //Notification Status Updating
            int Notification_ID = GetDossierNotificationID(DossierID);
            if (Notification_ID != 0)
            {
                UpdateRA_NotificationStatus(Notification_ID, 2);
            }
            ViewDossierModel objViewDossierModel = new ViewDossierModel();
            Aizant_Bl objAizant_Bl = new Aizant_Bl();
            var dbRegulatory = new AizantIT_DevEntities();
            List<SelectListItem> objDossierList = new List<SelectListItem>();
            var DossierDetails = (from PD in dbRegulatory.AizantIT_ProductDossier
                                  join EM in dbRegulatory.AizantIT_EmpMaster on PD.AuthorEmpID equals EM.EmpID
                                  join EM1 in dbRegulatory.AizantIT_EmpMaster on PD.ApproverEmpID equals EM1.EmpID
                                  join PM in dbRegulatory.AizantIT_ProductMaster on PD.ProductID equals PM.ProductID
                                  join C in dbRegulatory.AizantIT_Client on PD.ClientID equals C.ClientID
                                  join C1 in dbRegulatory.AizantIT_Client on PD.ApplicantID equals C1.ClientID
                                  join DF in dbRegulatory.AizantIT_DosageForm on PD.DosageFormID equals DF.DosageFormID
                                  join M in dbRegulatory.AizantIT_Market on PD.MarketID equals M.MarketID
                                  join DPM in dbRegulatory.AizantIT_DP_ManufacturingSite on PD.DP_ManufacturingSiteID equals DPM.DP_ManufacturingSiteID
                                  join CT in dbRegulatory.AizantIT_Countries on PD.CountryID equals CT.CountryID
                                  join PS in dbRegulatory.AizantIT_ProdStrength on PD.ProductDossierID equals PS.ProductDossierID
                                  join UOM in dbRegulatory.AizantIT_UOMMaster on PS.UOMID equals UOM.UOMID
                                  where PD.ProductDossierID == DossierID
                                  select new
                                  {
                                      PD.ProductDossierID,
                                      PD.CurrentStatus,
                                      DossierStatus = (PD.DossierStatus == "U" ? "Under Review" : "Approved"),
                                      PD.ApplicationNum,

AizantIT_PharmaApp/Areas/Regulatory/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

AizantIT_PharmaApp/Areas/Regulatory/Views/Shared/_RegulatoryLayout.cshtml
@{
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}
<link href=@Url.Content("~/AppCSS/Regulatory/regulatorystylesheet.css") rel="stylesheet" />
<!---Sub-Menu Starts-->
<div class="col-12 float-left padding-none" style="margin-top:50px;">
    <div class="col-12 reg_menu_list float-left top">
        @if (Session["EmpModuleRoles"] != null)
        {
            string[] ModuleRoles = (string[])Session["EmpModuleRoles"];
            <div class="col-12 text-center">
                <ul class="col-12">
                    @if (ModuleRoles.Contains(((int)Aizant_Enums.AizantEnums.RA_UserRole.RA_Lead).ToString())
                    || ModuleRoles.Contains(((int)Aizant_Enums.AizantEnums.RA_UserRole.RA_Approver).ToString())
                    || ModuleRoles.Contains(((int)Aizant_Enums.AizantEnums.RA_UserRole.RA_HOD).ToString()))
                    {
                        <li><a href="~/Regulatory/RegulatoryMain/RegulatoryDashBoard" class="dashboard left_border">Dashboard</a></li>
                    }
                    @if (ModuleRoles.Contains(((int)Aizant_Enums.AizantEnums.RA_UserRole.RA_Admin).ToString()))
                    {
                        <li class="reg_test">
                            <a href="#" class="product">Admin Setup</a>
                            <div class="dropdowntest">
                                <ul class="reg_sub_nav">
                                    <li style="font-size:14px;">@Html.ActionLink("Regulatory Master", "RegulatoryMasterList", "RegulatoryMaster", routeValues: new { Area = "Regulatory" }, htmlAttributes: null)</li>
                                    <li style="font-size:14px;">@Html.ActionLink("Re-assign Employee", "ReAssignProductList", "RegulatoryMain", routeValues: new { Area = "Regulatory" }, htmlAttributes: null)</li>
                                </ul>
                            </div>
                        </li>
                    }
                    @if (ModuleRoles.Contains(((int)Aizant_Enums.AizantEnums.RA_UserRole.RA_Approver).ToString())
                    || (ModuleRoles.Contains(((int)Aizant_Enums.AizantEnums.RA_UserRole.RA_HOD).ToString()))
                    || ModuleRoles.Contains(((int)Aizant_Enums.AizantEnums.RA_UserRole.RA_Lead).ToString())
                    )
                    {
                        <li class="reg_test">
                            <a href="#" class="productlist">Regulatory</a>
                            <div class="dropdowntest">
                                <ul class="reg_sub_nav">
                                    @if (ModuleRoles.Contains(((int)Aizant_Enums.AizantEnums.RA_UserRole.RA_Approver).ToString())
                                    || ModuleRoles.Contains(((int)Aizant_Enums.AizantEnums.RA_UserRole.RA_Lead).ToString()))
                                    {
                                        <li class="reg_list">
                                            <a href="#" class="reg_accrdn">Product</a>
                                            <ul class="reg_sub_nav_child">
                                                @if (ModuleRoles.Contains(((int)Aizant_Enums.AizantEnums.RA_UserRole.RA_Lead).ToString()))
                                                {
                                                    <li style="font-size:14px;"> @Html.ActionLink("Create Product Details", "CreateDossierMain", "RegulatoryMain", routeValues: new { Area = "Regulatory" }, htmlAttributes: null) </li>
                                                    <li style="font-size:14px;">@Html.ActionLink("Pending List", "DossierMainList", "RegulatoryMain", routeValues: new { Area = "Regulatory", ShowType = 0 }, htmlAttributes: null)</li>
                                                    <li style="font-size:14px;"> @Html.ActionLink("Reverted List", "DossierMainList", "RegulatoryMain", routeValues: new { Area = "Regulatory", ShowType = 2 }, htmlAttributes: null) </li>
                                                }
                                                @if (ModuleRoles.Contains(((int)Aizant_Enums.AizantEnums.RA_UserRole.RA_Approver).ToString()))
                                                {
                                                    <li style="font-size:14px;"> @Html.ActionLink("Review List", "DossierMainList", "RegulatoryMain", routeValues: new { Area = "Regulatory", ShowType = 1 }, htmlAttributes: null) </li>
                                                }
                                                <li style="font-size:14px;"> @Html.ActionLink("Product Details Main List", "DossierMainList", "RegulatoryMain", routeValues: new { Area = "Regulatory", ShowType = 3 }, htmlAttributes: null) </li>
                                            </ul>
                                        </li>
                                    }
                                    @if (ModuleRoles.Contains(((int)Aizant_Enums.AizantEnums.RA_UserRole.RA_Approver).ToString())
                                    || ModuleRoles.Contains(((int)Aizant_Enums.AizantEnums.RA_UserRole.RA_Lead).ToString()))
                                    {
                                        <li class="reg_list">
                                            <a href="#" class="reg_accrdn">Deficiency</a>
                                            <ul class="reg_sub_nav_child">
                                                @if (ModuleRoles.Contains(((int)Aizant_Enums.AizantEnums.RA_UserRole.RA_Approver).ToString()))
                                                {
                                                    <li style="font-size:14px;"> @Html.ActionLink("Review List", "DeficiencyMainList", "RegulatoryMain", routeValues: new { Area = "Regulatory", ShowType = 12 }, htmlAttributes: null) </li>

                                                }
                                                @if (ModuleRoles.Contains(((int)Aizant_Enums.AizantEnums.RA_UserRole.RA_Lead).ToString()))
                                                {
                                                    <li style="font-size:14px;"> @Html.ActionLink("Pending List", "DeficiencyMainList", "RegulatoryMain", routeValues: new { Area = "Regulatory", ShowType = 11}, htmlAttributes: null) </li>
                                                    <li style="font-size:14px;">@Html.ActionLink("Reverted List", "DeficiencyMainList", "RegulatoryMain", routeValues: new { Area = "Regulatory", ShowType = 13 }, htmlAttributes: null)</li>
                                                }
                                            </ul>
                                        </li>
                                    }
                                    <li class="reg_list">
                                        <a href="#" class="reg_accrdn">Observation</a>
                                        <ul class="reg_sub_nav_child">
                                            @if (ModuleRoles.Contains(((int)Aizant_Enums.AizantEnums.RA_UserRole.RA_HOD).ToString()))
                                            {
                                                <li style="font-size:14px;"> @Html.ActionLink("Pending List", "ObservationMainList", "RegulatoryMain", routeValues: new { Area = "Regulatory", ShowType = 22 }, htmlAttributes: null) </li>
                                            }                                          
                                            @if (ModuleRoles.Contains(((int)Aizant_Enums.AizantEnums.RA_UserRole.RA_Lead).ToString()) || ModuleRoles.Contains(((int)Aizant_Enums.AizantEnums.RA_UserRole.RA_Approver).ToString()) || ModuleRoles.Contains(((int)Aizant_Enums.AizantEnums.RA_UserRole.RA_HOD).ToString()))
                                            {
                                                <li style="font-size:14px;"> @Html.ActionLink("Observation Main List", "ObservationMainList", "RegulatoryMain", routeValues: new{ Area = "Regulatory",ShowType = 23}, htmlAttributes: null) </li>
                                            }
                                        </ul>
                                    </li>
                                </ul>
                            </div>
                        </li>
                    }
                </ul>
            </div>
        }
    </div>
</div>
<!---sub-menu ends-->
<div class="col-xl-12 col-md-12 col-sm-12 col-lg-12 float-left col-12 padding-none reg_formlist top ">
    @RenderBody()
</div>
<script>
    $(function () {
        var path = window.location.pathname + window.location.search;
        var href_value = "";
        $(".dropdowntest ul li").each(function () {
            href_value = $(this).children("a").attr("href");
            if (path == href_value) {
                $(this).children("a").addClass("active").parents(".reg_sub_nav_child").prev("a").addClass("active");
                $(this).parents(".reg_test").children("a").addClass("active");
            }
        });
    });
</script>

AizantIT_PharmaApp/Areas/Regulatory/Views/Shared/_RegulatoryUnAuthorizedView.cshtml
@{
    ViewBag.Title = "Not a Authorized User";
    Layout = "~/Areas/Regulatory/Views/Shared/_RegulatoryLayout.cshtml";
}
<title>@ViewBag.Title</title>
<div class="col-xl-12 col-md-12 col-sm-12 col-lg-12 col-12  padding-none float-left">
    <h2 style="text-align:center">
        <span style="color:red;">You are not a </span>
        <span style="color:crimson;">Authorized</span>
        <span style="color:red;"> User to view this Page.</span>
    </h2>
</div>