AizantIT_PharmaApp/Areas/QMS/Controllers/Common/DocumentViewerController.cs
using Aizant_API_Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
//using AizantIT_PharmaApp.Areas.QMS.Models.QmsModel;

namespace AizantIT_PharmaApp.Areas.QMS.Controllers.Common
{
    public class DocumentViewerController : Controller
    {
        // GET: QMS/DocumentViewer
        //private AizantIT_QMS_EF db = new AizantIT_QMS_EF();
        private AizantIT_DevEntities dbEF = new AizantIT_DevEntities();
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult RichEditViewer(int ID)
        {
            Models.QmsModel.DocumentViewerBO obj = new Models.QmsModel.DocumentViewerBO();
            var DocFiles = (from a in dbEF.AizantIT_Incident_IncidentAttachments
                            where a.UniquePKID==ID
                            select new { a.IncidentMasterID,a.FileType,a.FileName}).ToList();
            foreach (var item in DocFiles)
            {
                //string strFile = item.IncidentAttachament.ToString();
                //byte[] bytesF = System.IO.File.ReadAllBytes(strFile);
               // obj.fContent = item.IncidentAttachament;
                if(item.FileType==".docx")
                obj.DFormat = DevExpress.XtraRichEdit.DocumentFormat.OpenXml;
                if (item.FileType == ".doc")
                    obj.DFormat = DevExpress.XtraRichEdit.DocumentFormat.Doc;
                if (item.FileType == ".rtf")
                    obj.DFormat = DevExpress.XtraRichEdit.DocumentFormat.Rtf;
                if (item.FileType == ".txt")
                    obj.DFormat = DevExpress.XtraRichEdit.DocumentFormat.PlainText;
               
            }
            return View(obj);
        }

        public ActionResult RichEditViewer2(int? EventID, int ID)
        {
            Models.QmsModel.DocumentViewerBO obj = new Models.QmsModel.DocumentViewerBO();
            if (EventID == 1)
            {
                var DocFiles = (from a in dbEF.AizantIT_Incident_IncidentAttachments
                                where a.UniquePKID == ID
                                select new { a.IncidentMasterID, a.FileType, a.FileName }).ToList();
                foreach (var item in DocFiles)
                {
                    //string strFile = item.IncidentAttachament.ToString();
                    //byte[] bytesF = System.IO.File.ReadAllBytes(strFile);
                   // obj.fContent = item.IncidentAttachament;
                    if (item.FileType == ".docx")
                        obj.DFormat = DevExpress.XtraRichEdit.DocumentFormat.OpenXml;
                    if (item.FileType == ".doc")
                        obj.DFormat = DevExpress.XtraRichEdit.DocumentFormat.Doc;
                    if (item.FileType == ".rtf")
                        obj.DFormat = DevExpress.XtraRichEdit.DocumentFormat.Rtf;
                    if (item.FileType == ".txt")
                        obj.DFormat = DevExpress.XtraRichEdit.DocumentFormat.PlainText;
                    obj.UQID=ID.ToString();
                    obj.UQID = new Guid().ToString();

                }
            }
            return View(obj);
        }
        public ActionResult SpreadSheetViewer(int EventID, int ID)
        {
            Models.QmsModel.DocumentViewerBO obj = new Models.QmsModel.DocumentViewerBO();
            if (EventID == 1)
            {
                var DocFiles = (from a in dbEF.AizantIT_Incident_IncidentAttachments
                                where a.UniquePKID == ID
                                select new { a.IncidentMasterID, a.FileType, a.FileName }).ToList();
                foreach (var item in DocFiles)
                {                   
                    //obj.fContent = item.IncidentAttachament;
                    if (item.FileType == ".xlsx")
                        obj.XLFormat = DevExpress.Spreadsheet.DocumentFormat.Xlsx;
                    if (item.FileType == ".xls")
                        obj.XLFormat = DevExpress.Spreadsheet.DocumentFormat.Xls;
                    obj.UQID = new Guid().ToString();

                }
            }
            return View(obj);
        }
        public ActionResult ImageViewer(int EventID, int ID)
        {

            Models.QmsModel.DocumentViewerBO obj = new Models.QmsModel.DocumentViewerBO();
            if (EventID == 1)
            {
                var DocFiles = (from a in dbEF.AizantIT_Incident_IncidentAttachments
                                where a.UniquePKID == ID
                                select new { a.IncidentMasterID, a.FileType, a.FileName }).ToList();
                foreach (var item in DocFiles)
                {
                    
                    //obj.fContent = item.IncidentAttachament;


                }
            }
            return View(obj);
        }
        public ActionResult PDFViewer(int EventID, int ID)
        {

         
            if (EventID == 1)
            {

                string embed = "<object data=\"{0}\" type=\"application/pdf\" width=\"1000px\" height=\"600px\">";
                //embed += "If you are unable to view file, you can download from <a href = \"{0}\">here</a>";
                //embed += " or download <a target = \"_blank\" href = \"http://get.adobe.com/reader/\">Adobe PDF Reader</a> to view the file.";
                embed += "</object>";
                TempData["Embed"] = string.Format(embed, VirtualPathUtility.ToAbsolute("~/ASPXHandlers/QMSPDFViewHandler.ashx?EventID=1&DOCID=" + ID));
            }
            return View();
        }
    }
}

AizantIT_PharmaApp/Areas/QMS/Views/DocumentViewer/ImageViewer.cshtml
@model AizantIT_PharmaApp.Areas.QMS.Models.QmsModel.DocumentViewerBO

@*@{
        ViewBag.Title = "ImageViewer";
       // Layout = "~/Areas/QMS/Views/Shared/_QMSLayout.cshtml";
    }*@
@Styles.Render("~/Content/DevExtremeBundleStyles")
@Scripts.Render("~/Scripts/DevExtremeBundleScripts_0")
@Scripts.Render("~/Scripts/DevExtremeBundleScripts_1")
@Scripts.Render("~/Scripts/DevExtremeBundleScripts_2")
<h2>ImageViewer</h2>
<div class="col-xl-12 col-md-12 col-sm-12 col-lg-12 float-right col-12 top padding-none">
    <button type="button" class="btn btn-signup_popup float-right" onclick="location.href = document.referrer; return false;">close</button>
</div>

@Html.DevExpress().BinaryImage(settings =>
              {
                  settings.Name = "BinaryImage";
                  settings.ContentBytes = (Model.fContent);
              }).GetHtml()

AizantIT_PharmaApp/Areas/QMS/Views/DocumentViewer/PDFViewer.cshtml
@model AizantIT_PharmaApp.Areas.QMS.Models.QmsModel.DocumentViewerBO

@{
    ViewBag.Title = "PDFViewer";
    // Layout = "~/Areas/QMS/Views/Shared/_QMSLayout.cshtml";
}

<h2>PDFViewer</h2>
<div class="col-xl-12 col-md-12 col-sm-12 col-lg-12 float-right col-12 top padding-none">
    <button type="button" class="btn btn-signup_popup float-right" onclick="location.href = document.referrer; return false;">close</button>
</div>

                @Html.Raw(TempData["Embed"])
                @*<object data='@Url.Action("PDFViewer", "DocumentViewer")#zoom=150' width="100%" height="525" id="iFramePdf" #zoom="200" frameBorder="1" type="application/pdf"></object>*@
           

AizantIT_PharmaApp/Areas/QMS/Views/DocumentViewer/RichEditViewer.cshtml
@model AizantIT_PharmaApp.Areas.QMS.Models.QmsModel.DocumentViewerBO
<!--------Start View File Upload popup-------------->
@Styles.Render("~/Content/DevExtremeBundleStyles")
@Scripts.Render("~/Scripts/DevExtremeBundleScripts_0")
@Scripts.Render("~/Scripts/DevExtremeBundleScripts_1")
@Scripts.Render("~/Scripts/DevExtremeBundleScripts_2")
<div id="myModalViewDocuments" class="modal department fade" role="dialog">
    <div class="modal-dialog modal-lg">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">View Supporting Documents</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
                @Html.DevExpress().GetStyleSheets(
                            new StyleSheet { ExtensionSuite = ExtensionSuite.NavigationAndLayout },
                            new StyleSheet { ExtensionSuite = ExtensionSuite.Editors },
                            new StyleSheet { ExtensionSuite = ExtensionSuite.RichEdit },
                            new StyleSheet { ExtensionSuite = ExtensionSuite.Report }

                        )


                @Html.DevExpress().GetScripts(
                                       new Script { ExtensionSuite = ExtensionSuite.NavigationAndLayout },
                                       new Script { ExtensionSuite = ExtensionSuite.Editors },
                                       new Script { ExtensionSuite = ExtensionSuite.RichEdit },
                                       new Script { ExtensionSuite = ExtensionSuite.Report }
                                   )

                <script type="text/javascript" src="~/DevExtremeScripts/aspnet/dx.aspnet.mvc.js"></script>
                <script type="text/javascript" src="~/DevExtremeScripts/aspnet/dx.aspnet.data.js"></script>
                <div>
                    @Html.DevExpress().RichEdit(settings =>
              {
                  settings.Name = "RichEdit";
                  settings.CallbackRouteValues = new { Controller = "DocumentViewer", Action = "RichEditViewer" };
              }).Open(new Guid().ToString(), Model.DFormat, () => { return new MemoryStream(Model.fContent); }).GetHtml();
                </div>
            </div>
            <div class="modal-footer padding-none top">
                @*<button type="button" class="btn btn-signup_popup" onclick="funUploadFiles();">Add</button>*@
                <button type="button" class="btn btn-cancel_popup" data-dismiss="modal">Cancel</button>
            </div>
        </div>

    </div>
</div>
<!--------End View File Upload popup-------------->

AizantIT_PharmaApp/Areas/QMS/Views/DocumentViewer/RichEditViewer2.cshtml
@model AizantIT_PharmaApp.Areas.QMS.Models.QmsModel.DocumentViewerBO

@{
    ViewBag.Title = "RichEditViewer2";
    //  Layout = "~/Areas/QMS/Views/Shared/_QMSLayout.cshtml";
}
@Styles.Render("~/Content/DevExtremeBundleStyles")
@Scripts.Render("~/Scripts/DevExtremeBundleScripts_0")
@Scripts.Render("~/Scripts/DevExtremeBundleScripts_1")
@Scripts.Render("~/Scripts/DevExtremeBundleScripts_2")
<h2>RichEditViewer</h2>
<div class="col-xl-12 col-md-12 col-sm-12 col-lg-12 float-right col-12 top padding-none">
    <button type="button" class="btn btn-signup_popup float-right" onclick="location.href = document.referrer; return false;">close</button>
</div>

@Html.DevExpress().GetStyleSheets(
                new StyleSheet { ExtensionSuite = ExtensionSuite.NavigationAndLayout },
                new StyleSheet { ExtensionSuite = ExtensionSuite.Editors },
                new StyleSheet { ExtensionSuite = ExtensionSuite.RichEdit },
                new StyleSheet { ExtensionSuite = ExtensionSuite.Report }

            )

@Html.DevExpress().GetScripts(
                new Script { ExtensionSuite = ExtensionSuite.NavigationAndLayout },
                new Script { ExtensionSuite = ExtensionSuite.Editors },
                new Script { ExtensionSuite = ExtensionSuite.RichEdit },
                new Script { ExtensionSuite = ExtensionSuite.Report }
            )

@Html.DevExpress().RichEdit(settings =>
     {
         settings.Name = "RichEdit";
         settings.CallbackRouteValues = new { Controller = "DocumentViewer", Action = "RichEditViewer2" };
         settings.RibbonMode = DevExpress.Web.ASPxRichEdit.RichEditRibbonMode.None;
         settings.ReadOnly = true;
         settings.WorkDirectory = "~/App_Data/";
     }).Open(Model.UQID, Model.DFormat, () => { return new MemoryStream(Model.fContent); }).GetHtml();

AizantIT_PharmaApp/Areas/QMS/Views/DocumentViewer/SpreadSheetViewer.cshtml
@model AizantIT_PharmaApp.Areas.QMS.Models.QmsModel.DocumentViewerBO

@{
    ViewBag.Title = "SpreadSheetViewer";
    // Layout = "~/Areas/QMS/Views/Shared/_QMSLayout.cshtml";
}
@Styles.Render("~/Content/DevExtremeBundleStyles")
@Scripts.Render("~/Scripts/DevExtremeBundleScripts_0")
@Scripts.Render("~/Scripts/DevExtremeBundleScripts_1")
@Scripts.Render("~/Scripts/DevExtremeBundleScripts_2")
<h2>SpreadSheetViewer</h2>
<div class="col-xl-12 col-md-12 col-sm-12 col-lg-12 float-right col-12 top padding-none">
    <button type="button" class="btn btn-signup_popup float-right" onclick="location.href = document.referrer; return false;">close</button>
</div>
@Html.DevExpress().GetStyleSheets(
                new StyleSheet { ExtensionSuite = ExtensionSuite.NavigationAndLayout },
                new StyleSheet { ExtensionSuite = ExtensionSuite.Editors },
                new StyleSheet { ExtensionSuite = ExtensionSuite.Spreadsheet },
                new StyleSheet { ExtensionSuite = ExtensionSuite.Report }

            )

@Html.DevExpress().GetScripts(
                new Script { ExtensionSuite = ExtensionSuite.NavigationAndLayout },
                new Script { ExtensionSuite = ExtensionSuite.Editors },
                new Script { ExtensionSuite = ExtensionSuite.Spreadsheet },
                new Script { ExtensionSuite = ExtensionSuite.Report }
            )

<script type="text/javascript" src="~/Scripts/aspnet/dx.aspnet.mvc.js"></script>
<script type="text/javascript" src="~/Scripts/aspnet/dx.aspnet.data.js"></script>
<div class="col-xl-12 col-md-12 col-sm-12 col-lg-12 float-right col-12 top padding-none">
    <button type="button" class="btn btn-signup_popup float-right" onclick="location.href = document.referrer; return false;">close</button>
</div>

@Html.DevExpress().Spreadsheet(settings =>
          {
              settings.Name = "Spreadsheet";
              settings.CallbackRouteValues = new { Controller = "DocumentViewer", Action = "SpreadSheetViewer" };
              settings.RibbonMode = DevExpress.Web.ASPxSpreadsheet.SpreadsheetRibbonMode.None;
              settings.ReadOnly = true;
              settings.WorkDirectory = "~/App_Data/";
          }).Open(Model.UQID, Model.XLFormat, () => { return new MemoryStream(Model.fContent); }).GetHtml();